config/routes.rb
BitcoinAutoSellBroker::Application.routes.draw do

  get "coinbase/info"
  namespace :coinbase do
    resources :requests
  end

  resources :blockchain, only: :index

  resources :transactions do
    resource :deposits, only: [:new]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'users#signin', :as => :new_user_session
    get 'sign_in', :to => 'users#signin', :as => :new_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_session
  end

  root 'transactions#index'

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  #TODO: values are store as floats, it is better to keep them as integers and use Money gem
  WAITING_FOR_PAYMENT="waiting_payment".freeze
  AMOUNT_RECIEVED = "payment_receieved".freeze
  WRONG_AMOUNT_RECIEVED = "wrong_payment_received".freeze
  COMPLETED = "completed"

  def success?
    status == COMPLETED
  end

  def ready_to_sell?
    status == AMOUNT_RECIEVED
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :omniauthable, :rememberable, :trackable, :omniauth_providers => [:coinbase]
  serialize :credentials

  validates :uid, presence: true

  has_many :transactions

  def self.find_for_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
    end
  end

  def update_credentials!(credentials)
    self.credentials = credentials
    self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def coinbase
    coinbase = Coinbase::OAuthClient.new(
      Figaro.env.COINBASE_CLIENT_ID,
      Figaro.env.COINBASE_CLIENT_SECRET, current_user.credentials)
  end

  def coinbase_wallet
    response = coinbase.get("/account/receive_address")
    response["address"]
  end

  def coinbase_primary_account
    coinbase.accounts["accounts"].select{|account| account["primary"]}.first
  end

  def coinbase_primary_account_name
    coinbase_primary_account["name"]
  end
end

app/controllers/blockchain_controller.rb
#For validating that users made a payment
class BlockchainController < ApplicationController
  def index
    value = params[:value].to_f
    value = value/100000000 #satoshi!
    input_address= params[:input_address]
    destination_address = params[:destination_address]

    Rails.logger.info "Value: #{value}BTC"
    Rails.logger.info "Input address: #{input_address}"
    Rails.logger.info "Destination address: #{destination_address}"

    transaction = Transaction.find_by(incoming_address: input_address)
    if transaction.amount == value
      transaction.status = Transaction::AMOUNT_RECIEVED
    else
      transaction.status = Transaction::WRONG_AMOUNT_RECIEVED
    end
    transaction.save

    if transaction.ready_to_sell?
      #as soon as the user payment is received, attempt to sell it
      #TODO: create an asynchronous job
      BestPriceJob.perform(transaction.id)
    end

    #blockchain need this response
    render json: "*ok*"
  end
end

app/controllers/deposits_controller.rb
#Deposits made by the user into our account so we can sell for them
class DepositsController < ApplicationController
  before_action :authenticate_user!

  def new
    @transaction = current_user.transactions.find(params[:transaction_id])

    #TODO: better to do with a state machine
    if @transaction.status != Transaction::WAITING_FOR_PAYMENT

      #get a new address that will forward all incoming payment to our address
      response = RestClient.get 'https://blockchain.info/api/receive', {
        params: {
          method: "create",
          address: Figaro.env.BROKER_PAYMENT_BITCOIN_ADDRESS,
          callback: "http://#{Figaro.env.HOST}/blockchain"
        }
      }
      Rails.logger.info response

      json = JSON.parse(response)
      @broker_wallet = json["input_address"]
      @transaction.incoming_address = @broker_wallet
      @transaction.status = Transaction::WAITING_FOR_PAYMENT
      @transaction.save
    else
      @broker_wallet = @transaction.incoming_address
    end

    @qr = RQRCode::QRCode.new(@broker_wallet)
  end
end

app/controllers/transactions_controller.rb
#Transactions that users initiate and can see status of
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def new
    @transaction = current_user.transactions.build
  end

  def create
    @transaction = current_user.transactions.build
    @transaction.update_attributes(transaction_params)
    redirect_to new_transaction_deposits_path(@transaction)
  end

  def index
    @transactions = current_user.transactions
  end

  private

  def transaction_params
    params.require(:transaction).permit(:amount)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
require 'coinbase'

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def coinbase
    @user = User.find_for_oauth(request.env["omniauth.auth"])
    @user.update_credentials! (request.env["omniauth.auth"]["credentials"])

   if @user.persisted?
     sign_in_and_redirect @user, :event => :authentication
   else
     session["devise.omniauth_data"] = request.env["omniauth.auth"]
   end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def signin
    redirect_to user_omniauth_authorize_path(:coinbase)
  end

end

app/views/coinbase/info.html.erb
<h2>Your balance is: BTC<%= @balance.to_s %></h2>

<%= link_to "Request money", new_coinbase_request_path, class: "button" %>

app/views/coinbase/requests/_draw_qr.html.erb
<style type="text/css">
  table#bitcoin-qr {
    margin-left: 1em;
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
  }
  table#bitcoin-qr  td {
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
    padding: 0;
    margin: 0;
    width: 5px;
    height: 5px;
  }
  table#bitcoin-qr td.black { background-color: #000; }
  table#bitcoin-qr td.white { background-color: #fff; }
</style>

<div>
  <table id="bitcoin-qr">
    <% qr.modules.each_index do |x| -%>
      <tr>
        <% qr.modules.each_index do |y| -%>
          <% if qr.dark?(x,y) -%>
            <td class="black">
            </td>
          <% else -%>
            <td class="white">
            </td>
          <% end -%>
        <% end -%>
      </tr>
    <% end -%>
  </table>
</div>

app/views/coinbase/requests/create.html.erb
Please ask payment to be sent to: <strong><%= @new_wallet %></strong>.

<%= render "draw_qr", qr: @qr %>

<br/>

Payment will be sent to <strong><%= @wallet_name %>, <%= @wallet_balance.format %>(<%= @wallet %>)</strong>

app/views/coinbase/requests/new.html.erb
<header>
  <h1>Request payment</h1>
  <strong>Paranoid Mode</strong>
  <%= image_tag "paranoid.jpeg", width: "30px" %>
  <div>A payment request will be made to preserve you privacy:</div>
  <ul>
    <li>New Bitcoin wallet will be generated using blockchain.info</li>
    <li>Requestor will send payment to the new wallet</li>
    <li>Bitcoin will be trasferred to your Coinbase account</li>
  </ul>
</header>
<div>
</div>

<br/>
Choose wallet: <%= @wallet %>
<br/>

<table>
  <th>Name</th>
  <th>Balance</th>
  <th>Primary</th>
  <th>Action</th>
  <% @accounts.each do |account| %>
    <tr>
      <% id = account["id"] %>
      <% balance = account["balance"].format %>
      <% name = account["name"] %>
      <% primary = account["primary"] %>
      <td>
        <%= name %>
      </td>
      <td>
        <%= balance %>
      </td>
      <td>
        <% if primary %>
          yes
        <% end %>
      </td>
      <td>
        <%= link_to "Request payment", coinbase_requests_path(id: id), method: :post %>
      </td>
    </tr>
  <% end %>
</table>

app/views/deposits/_draw_qr.html.erb
<style type="text/css">
  table#bitcoin-qr {
    margin-left: 1em;
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
  }
  table#bitcoin-qr  td {
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
    padding: 0;
    margin: 0;
    width: 5px;
    height: 5px;
  }
  table#bitcoin-qr td.black { background-color: #000; }
  table#bitcoin-qr td.white { background-color: #fff; }
</style>

<div>
  <table id="bitcoin-qr">
    <% qr.modules.each_index do |x| -%>
      <tr>
        <% qr.modules.each_index do |y| -%>
          <% if qr.dark?(x,y) -%>
            <td class="black">
            </td>
          <% else -%>
            <td class="white">
            </td>
          <% end -%>
        <% end -%>
      </tr>
    <% end -%>
  </table>
</div>

app/views/deposits/new.html.erb
Please send <%= @transaction.amount %>BTC to <strong><%= @broker_wallet %></strong>.

<%= render "draw_qr", qr: @qr %>

<%= link_to "I sent BTC", transactions_url, class: "button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "BTCAutoSellBroker" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to "Home", root_path %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="">
            <%= link_to "My transactions", transactions_url %>
          </li>

          <li class="">
            <%= link_to "Sign out", destroy_session_path %>
          </li>
        </ul>

        <ul class="left">
        </ul>
      </section>
    </nav>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/transactions/index.html.erb
<%= link_to "Sell Bitcoin", new_transaction_path %>
<table>
  <% @transactions.each do |tx| %>
    <tr>
      <td>
        B⃦<%= tx.amount %>
      </td>
      <td>
        <%= tx.status %>
      </td>
      <td>
        <% if tx.success? %>
          <%= Money.new(tx.usd_amount*100).format %>
        <% end %>
      </td>
    </tr>
  <%end%>
</table>

app/views/transactions/new.html.erb
<div class="row">
  <div class="small-6 column">
    How much do you want to sell?
    <%= simple_form_for @transaction do |f| %>
      <%= f.input :amount, label: "Amount in BTC"%>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
Which wallet do you have?

<br/>

<%= link_to coinbase_info_path do  %>
  <%= image_tag "wallets/coinbase.png" %>
<% end %>